### ISSUE TITLE
6502 for Apple

### ISSUE THREAD

**Issue by albertvanderhorst** [ForthHub/FIG-Forth#1]
The name of the repository is slightly misleading, because it only contains a Forth implemented as an assembler plus metacompilation for the Apple II platform.  This is valuable and better naming could make the content better findable via search engines.

**Comment by larsbrinkhoff** [comment]
Maybe FIG-Forth-Model?  I don't think an overly long name would be much better, but there could be a description and a README file.

**Comment by albertvanderhorst** [comment]
It could  be of course that this archive aspires to contain all fig-Forth models.
In that case a readme should tell that. I could contribute.

**Comment by larsbrinkhoff** [comment]
That was not what I had in mind, but maybe that's a good idea.
